services:
  jhon_mc_carthy:
    build: .
    ports:
      - "5000:5000"
    restart: always

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

    ulimits:
      nproc: 64
      nofile:
        soft: 1024
        hard: 1024

