services:
  inspector:
    build: .
    ports:
      - "5001:5001"
    restart: always

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

    ulimits:
      nproc: 64
      nofile:
        soft: 1024
        hard: 1024

